import 'package:flutter/widgets.dart';

import 'app_localizations.dart';

/// Extra helpers not generated by gen_l10n.
extension AppLocalizationsExt on AppLocalizations {
  /// `true` when the active locale is Arabic.
  bool get isArabic => localeName == 'ar';

  /// The active [Locale] — mirrors the hand-rolled class's `locale` getter.
  /// Used by screens that pass `locale.languageCode` to date formatters.
  Locale get locale => Locale(localeName);
}
